const { chromium } = require('playwright');
(async()=>{
  const b = await chromium.launch();
  const ctx = await b.newContext({ viewport:{width:1300,height:900} });
  const p = await ctx.newPage();
  const errores=[]; p.on('pageerror', e=>errores.push(e.message)); p.on('console', m=>{ if(m.type()==='error') errores.push(m.text()); });
  await p.route(/fonts\.(googleapis|gstatic)/, r=>r.abort());
  await p.goto((process.env.BASE||'http://localhost:8765')+'/index.html');
  await p.click('[data-accion=nuevo-cliente]');
  await p.fill('#cNombre','Grupo Industrial Norte'); await p.fill('#cRfc','gin010101aaa'); await p.fill('#cContacto','Ana López');
  await p.click('[data-modal=guardar]');
  await p.click('[data-accion=nuevo-sitio]'); await p.fill('#sNombre','Planta Apodaca'); await p.click('[data-modal=guardar]');
  await p.click('[data-accion=nueva-cotizacion]');
  await p.selectOption('#qSitio',{index:1});
  await p.fill('#qTipo','Correctivo');
  const r1='#qPartidas tr:nth-child(1)';
  await p.fill(r1+' [data-k=seccion]','Refacciones'); await p.fill(r1+' [data-k=cantidad]','2'); await p.fill(r1+' [data-k=concepto]','BOMBA CENTRIFUGA 1HP'); await p.fill(r1+' [data-k=precioCosto]','1000');
  await p.click('#qAgregar');
  const r2='#qPartidas tr:nth-child(2)';
  await p.fill(r2+' [data-k=concepto]','Sello mecánico'); await p.fill(r2+' [data-k=precioCosto]','200'); await p.fill(r2+' [data-k=precioClienteManual]','300');
  await p.check('#qInstIncluir'); await p.fill('#qInstPct','10'); await p.fill('#qInstFijo','500');
  await p.screenshot({path:(process.argv[2]||'.')+'/editor.png', fullPage:false});
  await p.click('[data-modal=guardar]');
  await p.waitForTimeout(300);
  const st = await p.evaluate(()=>{ const q=Profectus.estado.datos.cotizaciones[0]; const k=Profectus.calcularCotizacion(q); return {folio:q.folio, nums:k.renglones.map(r=>r.numPart), costo:k.costo, cliente:k.cliente, util:k.utilidad, partidas:q.partidas.map(x=>x.concepto)}; });
  console.log(JSON.stringify(st));
  await p.screenshot({path:(process.argv[2]||'.')+'/detalle.png', fullPage:true});
  await p.click('[data-accion=previa-cotizacion]');
  const [doc] = await Promise.all([ ctx.waitForEvent('page'), p.click('[data-accion=doc][data-lado=cliente]') ]);
  await doc.waitForLoadState(); await doc.waitForTimeout(300);
  await doc.screenshot({path:(process.argv[2]||'.')+'/doc.png', fullPage:true});
  await doc.pdf({path:(process.argv[2]||'.')+'/doc.pdf', format:'Letter'});
  await p.click('[data-accion=ir][data-modulo=clientes]');
  await p.screenshot({path:(process.argv[2]||'.')+'/clientes.png'});
  await p.click('[data-accion=ir][data-modulo=admin]');
  await p.click('[data-pestana=parametros]');
  await p.screenshot({path:(process.argv[2]||'.')+'/admin.png'});
  await p.click('#btnTema'); await p.click('[data-accion=ir][data-modulo=cotizaciones]');
  await p.screenshot({path:(process.argv[2]||'.')+'/oscuro.png'});
  await p.setViewportSize({width:390,height:844}); await p.screenshot({path:(process.argv[2]||'.')+'/movil.png'});
  console.log('errores', errores);
  await b.close();
})();
